In [1]:
import numpy as np

# Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:

# Q2
print("Data type of each element in list_:")
for item in list_:
    print(type(item))
print("Data type of each element in array_list:")
for item in array_list:
    print(type(item))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:

# Q3
array_list = np.array(object=list_, dtype=int)
print("Data type of each element in list_ after conversion:")
for item in list_:
    print(type(int(item)))
print("Data type of each element in array_list after conversion:")
for item in array_list:
    print(type(item))


Data type of each element in list_ after conversion:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Data type of each element in array_list after conversion:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:

# Q4
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)



Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
# Q5
zeros_array = np.zeros((3, 3))
print("Zeros array:")
print(zeros_array)



Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Q6
identity_matrix = np.identity(5)
print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
